api_version = "2025-01"

[[extensions]]
name = "t:name"
handle = "regional-cart-transform"
type = "function"
uid = "30de25dc-225f-18fd-0f07-36d874bdb56c634ba302"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
